CREATE TABLE Pais(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Nome VARCHAR(255)
);

INSERT INTO PAIS (Id,Nome) VALUES
	 (1058,'BRASIL'),
	 (1600,'CHINA'),
	 (1601,'PAQUISTAO'),
	 (99,'EX'),
	 (5860,'PARAGUAI');